//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibraryApp.McvWebUI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Members()
        {
            this.Movements = new HashSet<Movements>();
            this.Penalties = new HashSet<Penalties>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="Bu alan boþ olamaz!")]
        [StringLength(20,ErrorMessage ="En fazla 20 karakter olmalýdýr!",MinimumLength =2)]
        public string MemberName { get; set; }
        [Required(ErrorMessage = "Bu alan boþ olamaz!")]
        [StringLength(20, ErrorMessage = "En fazla 20 karakter olmalýdýr!", MinimumLength = 2)]
        public string MemberLastName { get; set; }
        public string School { get; set; }
        [Required(ErrorMessage = "Bu alan boþ olamaz!")]
        [StringLength(50, ErrorMessage = "En fazla 50 karakter olmalýdýr!", MinimumLength = 2)]
        public string Mail { get; set; }
        [Required(ErrorMessage = "Bu alan boþ olamaz!")]
        public string Phone { get; set; }
        public string Image { get; set; }
        [Required(ErrorMessage = "Bu alan boþ olamaz!")]
        [StringLength(20, ErrorMessage = "En fazla 6-20 karakter arasýnda olmalýdýr!", MinimumLength = 6)]
        public string NickName { get; set; }
        [Required(ErrorMessage = "Bu alan boþ olamaz!")]
        [StringLength(20, ErrorMessage = "En fazla 20 karakter olmalýdýr!", MinimumLength = 5)]
        public string Password { get; set; }
        public string IdentityNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movements> Movements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penalties> Penalties { get; set; }
    }
}
