//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibraryApp.McvWebUI.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibraryAppDbEntities : DbContext
    {
        public LibraryAppDbEntities()
            : base("name=LibraryAppDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Movements> Movements { get; set; }
        public virtual DbSet<Penalties> Penalties { get; set; }
        public virtual DbSet<Safes> Safes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Writers> Writers { get; set; }
        public virtual DbSet<Abouts> Abouts { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
    
        public virtual ObjectResult<string> EnFazlaKitapYazar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnFazlaKitapYazar");
        }
    
        public virtual ObjectResult<string> EnFazlaKitapYayınevi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnFazlaKitapYayınevi");
        }
    
        public virtual ObjectResult<string> EnFazlaKitapAlanUye()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnFazlaKitapAlanUye");
        }
    
        public virtual ObjectResult<string> EnFazlaKİtapVerenPersonel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnFazlaKİtapVerenPersonel");
        }
    
        public virtual ObjectResult<string> EnFazlaOkunanKitap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnFazlaOkunanKitap");
        }
    }
}
