//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibraryApp.McvWebUI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Writers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Writers()
        {
            this.Books = new HashSet<Books>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="Yazar Adý Boþ Olamaz!")]
        [StringLength(30,ErrorMessage ="Yazar Adý 2 ile 30 karakter aralýðýnda olmalýdýr!",MinimumLength =2)]
        public string WriterName { get; set; }
        [Required(ErrorMessage = "Yazar Soyadý Boþ Olamaz!")]
        [StringLength(30, ErrorMessage = "Yazar Soyadý 2 ile 30 karakter aralýðýnda olmalýdýr!", MinimumLength = 2)]
        public string WriterLastName { get; set; }
        public string Detail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Books> Books { get; set; }
    }
}
